### ISSUE TITLE
Merging pdf streams of buffers instead of files of disc.

### ISSUE THREAD

**Issue by rolandnsharp** [metaist/pdfmerge#17]
Hi, I'm trying to use this tool to merge pdfs that I'm creating in node.js on a server. The problem is that the server doesn't allow writing to disc so my pdfs are in streams. Is it possible to merge two pdf streams?

Thanks

**Comment by rolandnsharp** [comment]
sorry, wrong repo

**Comment by metaist** [comment]
No worries. But actually, I probably should make it possible to merge streams someday :-)
