### ISSUE TITLE
Merging generates some blank pages instead of source file

### ISSUE THREAD

**Issue by dcanl** [metaist/pdfmerge#32]
Hello,

pdfmerge() function replaces some files with a blank page in the destination file for no reason. This behavior is totally random: same files in input can generate 1 to many blank pages in output file, or sometimes none.

I am currently trying with 4005 files in input, representing 4296 total pages. All input files are correct, the list contains all files path. Same problem appears with fewer files / pages.

Here is my code:

```
for root, directory, files in os.walk(pathIn):
    for file in files:
        if file.endswith('.pdf'):
            pdfList.append(os.path.join(root, file))

pdfmerge(pdfList, pathOut+"\\"+fileOut)
```

Did you ever encounter this problem? Is there a solution?

**Comment by metaist** [comment]
Huh. Never seen anything like this. I'm assuming `pathOut` and `fileOut` are where you want to write the output pdf to.

Just as a sanity check, does this code produce the same or different results:

```python
from pathlib import Path # for python > 3.4

pdfList = [str(p) for p in sorted(Path(pathIn).glob("*.pdf"))]
pdfmerge(pdfList, str(Path(pathOut) / fileOut))
```

**Comment by dcanl** [comment]
Thank you for your reply.

Result is the same...

**Comment by metaist** [comment]
Very weird. `pdfmerge` [just wraps `pypdf`](https://github.com/metaist/pdfmerge/blob/main/src/pdfmerge/__init__.py#L202). Is it possible to see some more detail about how these PDFs are being generated?

**Comment by dcanl** [comment]
Sadly no, files are generated by an AS/400, and hum... AS/400!! 🫠

Suprisingly, using pypdf directly doesn't seem to produce any blank page... I will use that for now.

**Comment by metaist** [comment]
Understood. Sorry we couldn't figure out where the blank pages were coming from. 

Closing this issue for now. Will re-open if anyone else experiences the same thing.
